version: '3.3'

services:
    mongodb:
        image: mvertes/alpine-mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db

    api:
        build: .
        depends_on:
            - mongodb
        environment:
            DEBUG: my-service:*
            MONGODB_URL: mongodb://mongodb:27017/my-service
            NODE_ENV: development
            SENTRY_TIMEOUT: 5
        ports:
            - 3000:3000

volumes:
    mongodb:
